
version: 2.1

orbs:
  node: circleci/node@6.1.0
  browser-tools: circleci/browser-tools@1.4.8

executors:
  linux:
    docker:
      - image: 'codeceptjs/codeceptjs'

commands:
  install_dependencies:
    steps:
      - upgrade_node
      - checkout
      - node/install-packages:
          pkg-manager: yarn
  upgrade_node:
    steps:
      - run: node --version
      - run: apt-get update && apt-get install -y curl
      - run: curl --version
      - node/install:
          node-version: '22.9'
      - run: node --version

jobs:
  setup:
    executor: linux
    steps:
      - install_dependencies
      - persist_to_workspace:
          root: ./
          paths:
            - ./*

  yarn_lint:
    executor: linux
    steps:
      - upgrade_node
      - attach_workspace:
          at: ./
      - run: yarn lint
      - run: npx puppeteer browsers install chrome

  yarn_test:
    executor: linux
    steps:
      - upgrade_node
      - attach_workspace:
          at: ./
      - run: yarn test
      - store_artifacts:
          path: ./output

  yarn_test_parallel:
    executor: linux
    steps:
      - upgrade_node
      - attach_workspace:
          at: ./
      - run: yarn test-run-multiple
      - store_artifacts:
          path: ./output
workflows:
  run_tests:
    jobs:
      - setup
      - yarn_lint:
          requires:
            - setup
      - yarn_test:
          requires:
            - setup
      - yarn_test_parallel:
          requires:
            - setup
