
version: 2.1

orbs:
  node: circleci/node@5.0.2

executors:
  linux:
    docker:
      - image: 'codeception/codeceptjs'

commands:
  install_dependencies:
    steps:
      - checkout
      - run: node --version
      - run: apt-get update && apt-get install -y curl
      - run: curl --version
#      - run: nvm --version
      - node/install:
#          install-yarn: true
          node-version: '16.15'
      - run: node --version
      - node/install-packages:
          pkg-manager: yarn

jobs:
  setup:
    executor: linux
    steps:
      - install_dependencies
      - persist_to_workspace:
          root: ./
          paths:
            - ./*

  yarn_lint:
    executor: linux
    steps:
      - attach_workspace:
          at: ./
      - run: yarn lint

  yarn_test:
    executor: linux
    steps:
      - attach_workspace:
          at: ./
      - run: yarn test

  yarn_test_parallel:
    executor: linux
    steps:
      - attach_workspace:
          at: ./
      - run: yarn test-run-multiple

workflows:
  run_tests:
    jobs:
      - setup
      - yarn_lint:
          requires:
            - setup
      - yarn_test:
          requires:
            - setup
      - yarn_test_parallel:
          requires:
            - setup
