
version: 2.1

orbs:
  node: circleci/node@6.1.0

executors:
  linux:
    docker:
      - image: 'codeceptjs/codeceptjs'

commands:
  install_dependencies:
    steps:
      - upgrade_node
      - checkout
      - node/install-packages:
          pkg-manager: yarn
  upgrade_node:
    steps:
      - run: node --version
      - run: apt-get update && apt-get install -y curl
      - run: curl --version
      - node/install:
          node-version: '22.9'
      - run: node --version
  install_chrome:
    steps:
      - run: npx puppeteer browsers install chrome

jobs:
  setup:
    executor: linux
    steps:
      - install_dependencies
      - persist_to_workspace:
          root: ./
          paths:
            - ./*

  yarn_lint:
    executor: linux
    steps:
      - upgrade_node
      - attach_workspace:
          at: ./
      - run: yarn lint

  yarn_test:
    executor: linux
    steps:
      - upgrade_node
      - install_chrome
      - attach_workspace:
          at: ./
      - run: yarn test

  yarn_test_parallel:
    executor: linux
    steps:
      - upgrade_node
      - install_chrome
      - attach_workspace:
          at: ./
      - run: yarn test-run-multiple

workflows:
  run_tests:
    jobs:
      - setup
      - yarn_lint:
          requires:
            - setup
      - yarn_test:
          requires:
            - setup
      - yarn_test_parallel:
          requires:
            - setup
