
version: 2.1

orbs:
  node: circleci/node@3.0.0
  puppeteer: threetreeslight/puppeteer@0.1.2

executors:
  linux:
    docker:
      - image: 'cimg/node:lts'

commands:
  install_dependencies:
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: sudo apt-get update
      - puppeteer/install

jobs:
  setup:
    executor: linux
    steps:
      - install_dependencies
      - persist_to_workspace:
          root: ./
          paths:
            - ./*

  yarn_lint:
    executor: linux
    steps:
      - attach_workspace:
          at: ./
      - run: yarn lint

  yarn_test:
    executor: linux
    steps:
      - attach_workspace:
          at: ./
      - run: yarn test

  yarn_test_parallel:
    executor: linux
    steps:
      - attach_workspace:
          at: ./
      - run: test-run-multiple

workflows:
  run_tests:
    jobs:
      - setup
      - yarn_lint:
          requires:
            - setup
      - yarn_test:
          requires:
            - setup
      - yarn_test_parallel:
          requires:
            - setup
